repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: name-tests-test
      - id: requirements-txt-fixer
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        language_version: 3.10.9
        args: [-t, py310]
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.4.0
    hooks:
      - id: pycln
  - repo: https://github.com/pycqa/isort
    rev: 5.13.1
    hooks:
      - id: isort
        files: "\\.(py)$"
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.940
  #   hooks:
  #     - id: mypy
  #       exclude: ^tests/
  #       args: [--strict]
